### ISSUE TITLE
M5Atomからblink_powerのPowerONができない。

### ISSUE THREAD

**Issue by nishi10000** [WHILL/whill-sdk-arduino#3]
https://github.com/WHILL/whill-sdk-arduino/tree/esp32/examples/blink_power
上記を参考にさせていだたき、M5Atomから操作を行っています。

サンプルの中で、
callback
shake
は動作しています。

しかし、blink_powerの
whill.setPower(true); 部分が動作しません。
※whill.setPower(false);の部分は動作します。 

サンプル以外でも下記サイトを参考にして実装しましたが、
whill.setPower(true);部分は動作しませんでした。
https://qiita.com/KatsuShun89/items/69222ce96ff3debcba11

なにか思い当たることはありますでしょうか？大変申し訳ございませんが、ご確認いただけないでしょうか？

**Comment by s-katsu** [comment]
お問い合わせありがとうございます。

こちらサンプルが古く、電源OFF後にONする場合はsetPower(true)を10ms間隔で2回呼ぶ必要があります。
このようにblink_powerを変更して電源が入るかご確認いただけますでしょうか。

```
  whill.setPower(true);  // Turn WHILL on
  whill.delay(10);
  whill.setPower(true);  // Turn WHILL on
  whill.delay(5000);
```

**Comment by nishi10000** [comment]
無事に電源のON/OFFが出来ました。ありがとうございました。
