### ISSUE TITLE
setSpeedProfile関数が使用できない。

### ISSUE THREAD

**Issue by nishi10000** [WHILL/whill-sdk-arduino#4]
https://github.com/WHILL/whill-sdk-arduino/blob/esp32/src/whill_commands.cpp

https://github.com/WHILL/whill-sdk-arduino/blob/b1001c8cecaf29e56063e06a2798ac6e6801e824/src/whill_commands.cpp#L76-L90

上記についてですが、speed_modeが抜けています。

下記であれば動作しました。

<pre><code class="cpp">
void WHILL::setSpeedProfile(SpeedProfile* profile, unsigned char speed_mode) {
    unsigned char payload[] = {0x04,
                               speed_mode,  //add
                               profile->forward_spped,
                               profile->forward_acceleration,
                               profile->forward_deceleration,
                               profile->reverse_speed,
                               profile->reverse_acceleration,
                               profile->reverse_deceleration,
                               profile->turn_speed,
                               profile->turn_acceleration,
                               profile->turn_deceleration};
    Packet packet(payload, sizeof(payload));
    packet.build();
    transferPacket(&packet);
}
</code></pre>

**Comment by GeorgeMandokoro** [comment]
このたびはご指摘いただきありがとうございます。
修正いたしましたので、クローズさせていただきます。
